exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

plugins:
  - jekyll-katex

katex:
  js_path: "assets/javascript"
  rendering_options:
    throw_error: true
    error_color: "#cc0000"

title: C E Salinas
description: Carlos Salinas' Homepage at Purdue University
url:  https://www.math.purdue.edu
baseurl: /~salinac
