exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: true
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/kafande/PU-Homepage"
  
title: Carlos' Homepage 
description: Carlos Salinas' Homepage at Purdue University
url:  https://www.math.purdue.edu
baseurl: /~salinac
